#!/bin/bash

# Get the directory of the script
HERE="$(dirname "$(readlink -f "${0}")")"

# Export the library path to include the AppImage internal libraries
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"

# Launch the PhotoSorter application
exec "${HERE}/usr/bin/PhotoSorter" "$@"
